package hiber;
// Generated Oct 29, 2016 11:27:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private Integer idFaculty;
     private String name;
     private Set<Specialty> specialties = new HashSet<Specialty>(0);

    public Faculty() {
    }

    public Faculty(String name, Set<Specialty> specialties) {
       this.name = name;
       this.specialties = specialties;
    }
   
    public Integer getIdFaculty() {
        return this.idFaculty;
    }
    
    public void setIdFaculty(Integer idFaculty) {
        this.idFaculty = idFaculty;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Specialty> getSpecialties() {
        return this.specialties;
    }
    
    public void setSpecialties(Set<Specialty> specialties) {
        this.specialties = specialties;
    }




}


