package hiber;
// Generated Oct 29, 2016 11:27:02 AM by Hibernate Tools 4.3.1



/**
 * Level generated by hbm2java
 */
public class Level  implements java.io.Serializable {


     private Integer idlevel;
     private String name;

    public Level() {
    }

    public Level(String name) {
       this.name = name;
    }
   
    public Integer getIdlevel() {
        return this.idlevel;
    }
    
    public void setIdlevel(Integer idlevel) {
        this.idlevel = idlevel;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


