package hiber;
// Generated Oct 29, 2016 11:27:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Specialty generated by hbm2java
 */
public class Specialty  implements java.io.Serializable {


     private Integer idspecialty;
     private Faculty faculty;
     private String name;
     private Set<Student> students = new HashSet<Student>(0);

    public Specialty() {
    }

	
    public Specialty(Faculty faculty, String name) {
        this.faculty = faculty;
        this.name = name;
    }
    public Specialty(Faculty faculty, String name, Set<Student> students) {
       this.faculty = faculty;
       this.name = name;
       this.students = students;
    }
   
    public Integer getIdspecialty() {
        return this.idspecialty;
    }
    
    public void setIdspecialty(Integer idspecialty) {
        this.idspecialty = idspecialty;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }




}


