package hiber;
// Generated Oct 29, 2016 11:27:02 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int idstudent;
     private Specialty specialty;
     private String firstName;
     private String lastName;
     private Date entryYear;
     private String eduLevel;
     private String paymentType;
     private String gender;
     private Date birthday;
     private String telephone1;
     private String telephone2;
     private String email1;
     private String email2;
     private String address;
     private String nationality;
     private String docType;
     private String docNumber;
     private Date docExpireTime;
     private String docIssueOrgnazation;
     private String fatherName;
     private String fatherWorkingPlace;
     private String fatherMobilePhone;
     private String fatherHomePhone;
     private String fatherEmail;
     private String fatherAdress;
     private String matherName;
     private String matherWorkingPlace;
     private String matherMobilePhone;
     private String matherHomePhone;
     private String matherEmail;
     private String matherAddress;
     private String imagePath;
     private Integer idEdu;
     private String studentId;
     private Set<Educationhistory> educationhistories = new HashSet<Educationhistory>(0);

    public Student() {
    }

	
    public Student(int idstudent, Specialty specialty) {
        this.idstudent = idstudent;
        this.specialty = specialty;
    }
    public Student(int idstudent, Specialty specialty, String firstName, String lastName, Date entryYear, String eduLevel, String paymentType, String gender, Date birthday, String telephone1, String telephone2, String email1, String email2, String address, String nationality, String docType, String docNumber, Date docExpireTime, String docIssueOrgnazation, String fatherName, String fatherWorkingPlace, String fatherMobilePhone, String fatherHomePhone, String fatherEmail, String fatherAdress, String matherName, String matherWorkingPlace, String matherMobilePhone, String matherHomePhone, String matherEmail, String matherAddress, String imagePath, Integer idEdu, String studentId, Set<Educationhistory> educationhistories) {
       this.idstudent = idstudent;
       this.specialty = specialty;
       this.firstName = firstName;
       this.lastName = lastName;
       this.entryYear = entryYear;
       this.eduLevel = eduLevel;
       this.paymentType = paymentType;
       this.gender = gender;
       this.birthday = birthday;
       this.telephone1 = telephone1;
       this.telephone2 = telephone2;
       this.email1 = email1;
       this.email2 = email2;
       this.address = address;
       this.nationality = nationality;
       this.docType = docType;
       this.docNumber = docNumber;
       this.docExpireTime = docExpireTime;
       this.docIssueOrgnazation = docIssueOrgnazation;
       this.fatherName = fatherName;
       this.fatherWorkingPlace = fatherWorkingPlace;
       this.fatherMobilePhone = fatherMobilePhone;
       this.fatherHomePhone = fatherHomePhone;
       this.fatherEmail = fatherEmail;
       this.fatherAdress = fatherAdress;
       this.matherName = matherName;
       this.matherWorkingPlace = matherWorkingPlace;
       this.matherMobilePhone = matherMobilePhone;
       this.matherHomePhone = matherHomePhone;
       this.matherEmail = matherEmail;
       this.matherAddress = matherAddress;
       this.imagePath = imagePath;
       this.idEdu = idEdu;
       this.studentId = studentId;
       this.educationhistories = educationhistories;
    }
   
    public int getIdstudent() {
        return this.idstudent;
    }
    
    public void setIdstudent(int idstudent) {
        this.idstudent = idstudent;
    }
    public Specialty getSpecialty() {
        return this.specialty;
    }
    
    public void setSpecialty(Specialty specialty) {
        this.specialty = specialty;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getEntryYear() {
        return this.entryYear;
    }
    
    public void setEntryYear(Date entryYear) {
        this.entryYear = entryYear;
    }
    public String getEduLevel() {
        return this.eduLevel;
    }
    
    public void setEduLevel(String eduLevel) {
        this.eduLevel = eduLevel;
    }
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getTelephone1() {
        return this.telephone1;
    }
    
    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }
    public String getTelephone2() {
        return this.telephone2;
    }
    
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getDocType() {
        return this.docType;
    }
    
    public void setDocType(String docType) {
        this.docType = docType;
    }
    public String getDocNumber() {
        return this.docNumber;
    }
    
    public void setDocNumber(String docNumber) {
        this.docNumber = docNumber;
    }
    public Date getDocExpireTime() {
        return this.docExpireTime;
    }
    
    public void setDocExpireTime(Date docExpireTime) {
        this.docExpireTime = docExpireTime;
    }
    public String getDocIssueOrgnazation() {
        return this.docIssueOrgnazation;
    }
    
    public void setDocIssueOrgnazation(String docIssueOrgnazation) {
        this.docIssueOrgnazation = docIssueOrgnazation;
    }
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }
    public String getFatherWorkingPlace() {
        return this.fatherWorkingPlace;
    }
    
    public void setFatherWorkingPlace(String fatherWorkingPlace) {
        this.fatherWorkingPlace = fatherWorkingPlace;
    }
    public String getFatherMobilePhone() {
        return this.fatherMobilePhone;
    }
    
    public void setFatherMobilePhone(String fatherMobilePhone) {
        this.fatherMobilePhone = fatherMobilePhone;
    }
    public String getFatherHomePhone() {
        return this.fatherHomePhone;
    }
    
    public void setFatherHomePhone(String fatherHomePhone) {
        this.fatherHomePhone = fatherHomePhone;
    }
    public String getFatherEmail() {
        return this.fatherEmail;
    }
    
    public void setFatherEmail(String fatherEmail) {
        this.fatherEmail = fatherEmail;
    }
    public String getFatherAdress() {
        return this.fatherAdress;
    }
    
    public void setFatherAdress(String fatherAdress) {
        this.fatherAdress = fatherAdress;
    }
    public String getMatherName() {
        return this.matherName;
    }
    
    public void setMatherName(String matherName) {
        this.matherName = matherName;
    }
    public String getMatherWorkingPlace() {
        return this.matherWorkingPlace;
    }
    
    public void setMatherWorkingPlace(String matherWorkingPlace) {
        this.matherWorkingPlace = matherWorkingPlace;
    }
    public String getMatherMobilePhone() {
        return this.matherMobilePhone;
    }
    
    public void setMatherMobilePhone(String matherMobilePhone) {
        this.matherMobilePhone = matherMobilePhone;
    }
    public String getMatherHomePhone() {
        return this.matherHomePhone;
    }
    
    public void setMatherHomePhone(String matherHomePhone) {
        this.matherHomePhone = matherHomePhone;
    }
    public String getMatherEmail() {
        return this.matherEmail;
    }
    
    public void setMatherEmail(String matherEmail) {
        this.matherEmail = matherEmail;
    }
    public String getMatherAddress() {
        return this.matherAddress;
    }
    
    public void setMatherAddress(String matherAddress) {
        this.matherAddress = matherAddress;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public Integer getIdEdu() {
        return this.idEdu;
    }
    
    public void setIdEdu(Integer idEdu) {
        this.idEdu = idEdu;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public Set<Educationhistory> getEducationhistories() {
        return this.educationhistories;
    }
    
    public void setEducationhistories(Set<Educationhistory> educationhistories) {
        this.educationhistories = educationhistories;
    }




}


